╔╦━╦━╦━╦━═━═━═━═━═━═━═━╦━╦━╦━╦╗
║║ ║ ║ ║  P A U S E D  ║ ║ ║ ║║
╠╬━╩━╩━╩━═━═━═━═━═━═━═━╩━╩━╩━╬╣
╠╣  ╭─────────────────────╮  ╠╣
╠╣  │   c o n t i n u e   │  ╠╣
╠╣  ╰─────────────────────╯  ╠╣
╠╣ ╔═══════════════════════╗ ╠╣
╠╣ ║     R E S T A R T     ║ ╠╣
╠╣ ╚═══════════════════════╝ ╠╣
╠╣  ╭─────────────────────╮  ╠╣
╠╣  │  l o a d \ s a v e  │  ╠╣
╠╣  ╰─────────────────────╯  ╠╣
╠╣  ╭─────────────────────╮  ╠╣
╠╣  │    o p t i o n s    │  ╠╣
╠╣  ╰─────────────────────╯  ╠╣
╠╣  ╭─────────────────────╮  ╠╣
╠╣  │  m a i n   m e n u  │  ╠╣
╠╣  ╰─────────────────────╯  ╠╣
╠╬━╦━╦━╦━═━═━═━═━═━═━═━╦━╦━╦━╬╣
║║ ║ ║ ║  P A U S E D  ║ ║ ║ ║║
╚╩━╩━╩━╩━═━═━═━═━═━═━═━╩━╩━╩━╩╝
